name: 'Terraform'

env:
  region: eu-west-1

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Validate
      run: terraform validate

    - name: Configure AWS secrets
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{env.region}}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -out "./plan"

    - uses: actions/upload-artifact@v3
      with:
        name: plan
        path: ./plan
        if-no-files-found: error

    - name: Show readable plan and save
      run: terraform show -json ./plan > tfplan.txt
    
